---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - edge.example.com
  resources:
  - edgedevices
  - fleetrollouts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - edge.example.com
  resources:
  - edgedevices/finalizers
  - fleetrollouts/finalizers
  verbs:
  - update
- apiGroups:
  - edge.example.com
  resources:
  - edgedevices/status
  - fleetrollouts/status
  verbs:
  - get
  - patch
  - update
